from django.contrib import admin
from django.utils.functional import cached_property
from django.db.models import ManyToOneRel


class HiddenAdminMixin(object):

    def get_model_perms(self, request):
        """
        Return empty perms dict thus hiding the model from admin index.
        """
        return {}


class HiddenAdmin(HiddenAdminMixin, admin.ModelAdmin):
    pass


class FKInlineAdminMixin(object):

    @cached_property
    def inlines(self):
        """
        Replaces inline attribute with autogenerated inlines for Foreign Key
        models.
        """
        inlines = []
        fields = self.model._meta.get_fields()

        for field in fields:
            if isinstance(field, ManyToOneRel):
                inline = self.get_inline(field)
                inlines.append(inline)

        return inlines

    def get_inline(self, field):
        """
        Creates an inline class for the field provided
        """
        class Inline(self.inline_class):
            model = field.field.model
            extra = 1
            show_change_link = True

        return Inline


class FKInlineAdmin(FKInlineAdminMixin, admin.ModelAdmin):
    pass
